#!/usr/bin/env bash
# Yousefeslam214&

sudo apt-get -y update;
sudo apt-get -y install nginx;
sudo ufw allow 'Nginx HTTP';
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';
sudo service nginx start;
