#!/usr/bin/env bash
# Bash script

counter=1
iter=0
echo "Hour: $iter"
while [ $counter -le 60 ]; do
    if [ $((counter % 60)) -eq 0 ]; then
        ((iter++))
        if [ $iter -eq 13 ]; then
            break
        fi
        echo "Hour: $iter"
        counter=0
    else
        echo "$counter"
    fi
    ((counter++))
done
