#!/usr/bin/env bash
# bash script

file_path="/home/yousef/Desktop/programing/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/school"



if [ -e "$file_path" ]; then
    if [ -d "$file_path" ]; then
        echo "school exists but it’s a directory"
    else
        echo "school file exists"
        if [ -s "$file_path" ]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    fi
    if [ -f "$file_path" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi



